### ISSUE TITLE
Bug in index.js file

### ISSUE THREAD

**Issue by Dstklr** [DmitryShashkov/ts-json-mapper#3]
In index.js file, the "BaseModel" function passes "correspondence.key" parameter to "this.deserializeValue".
seems that "correspondence.key" doesn't exists, and the parameters order sent to "BaseModel.prototype.deserializeValue" is incorrect - therefor creating an exception upon passing empty value in JSON file when mapping, due to the following statement:

  // if value is required and it is null, throw exception
        if (required && !value){
            throw new Error("Value for json field '" + jsonField + "' not found")
        }

**Comment by DmitryShashkov** [comment]
Seems like there were outdated .js and .d.ts files - this is fixed in version 0.0.7.
Thank you for reporting this bug!
